name = "Fabulously Optimized"
author = "robotkoer"
version = "5.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "71797e88d0dd642fc705d824509c8664ef581aac794f19126bab7f9e335bba70"

[versions]
fabric = "0.14.21"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20"]
